title: "David Aulicino"
description: "Network & Infrastructure Engineer | Portfolio & Blog"
url: "https://davidaulicino17.github.io"
baseurl: "/GitPages"

show_downloads: false

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

permalink: /:year/:month/:day/:title/
timezone: Europe/Rome

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - COVER_IMAGE_GUIDE.md
